filter:
    excluded_paths:
        - 'tests/*'
        - 'vendor/*'
checks:
    php: true
coding_style:
    php:
        spaces:
            around_operators:
                concatenation: true
            before_keywords:
                else: false
                catch: false
            within:
                brackets: true
build:
    tests:
        override:
            -
                command: 'phpunit --coverage-clover=fipe-api'
                coverage:
                    file: 'fipe-api'
                    format: 'clover'