dist: trusty
sudo: required

language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - 'hhmv'

addons:
  apt:
    packages:

before_script:
  - composer install
  - composer --version

script:
  - "phpunit --configuration phpunit.xml --coverage-text"
